CREATE TABLE IF NOT EXISTS `all_players` (
`id` INT NOT NULL AUTO_INCREMENT ,
`player_name` VARCHAR(32) NOT NULL ,
`player_uuid` CHAR(32) NOT NULL ,
`first_join` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`last_join` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`join_count` INT NOT NULL DEFAULT '0' ,
`join_time` INT NOT NULL DEFAULT '0' ,
PRIMARY KEY (`id`));